
/*
 * sanity checks for generated foreign headers:
 *  - verify struct sizes
 *
 * generated by %s -- DO NOT EDIT
 */
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <inttypes.h>
#include "arm32.h"
#include "arm64.h"
#include "x86_32.h"
#include "x86_64.h"
int main(int argc, char *argv[])
{
	printf("\n");printf("%-25s |", "structs");
	printf("%8s", "arm32");
	printf("%8s", "arm64");
	printf("%8s", "x86_32");
	printf("%8s", "x86_64");
	printf("\n");	printf("\n");	printf("%-25s |", "start_info");
#ifdef arm32_has_no_start_info
	printf("%8s",
# ifndef arm64_has_no_start_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct start_info_arm32));
	if (sizeof(struct start_info_arm32) != sizeof(struct start_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_start_info
	printf("%8s",
# ifndef arm32_has_no_start_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct start_info_arm64));
	if (sizeof(struct start_info_arm64) != sizeof(struct start_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_start_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct start_info_x86_32));
#endif
#ifdef x86_64_has_no_start_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct start_info_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "trap_info");
#ifdef arm32_has_no_trap_info
	printf("%8s",
# ifndef arm64_has_no_trap_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct trap_info_arm32));
	if (sizeof(struct trap_info_arm32) != sizeof(struct trap_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_trap_info
	printf("%8s",
# ifndef arm32_has_no_trap_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct trap_info_arm64));
	if (sizeof(struct trap_info_arm64) != sizeof(struct trap_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_trap_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct trap_info_x86_32));
#endif
#ifdef x86_64_has_no_trap_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct trap_info_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "cpu_user_regs");
#ifdef arm32_has_no_cpu_user_regs
	printf("%8s",
# ifndef arm64_has_no_cpu_user_regs
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct cpu_user_regs_arm32));
	if (sizeof(struct cpu_user_regs_arm32) != sizeof(struct cpu_user_regs_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_cpu_user_regs
	printf("%8s",
# ifndef arm32_has_no_cpu_user_regs
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct cpu_user_regs_arm64));
	if (sizeof(struct cpu_user_regs_arm64) != sizeof(struct cpu_user_regs_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_cpu_user_regs
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct cpu_user_regs_x86_32));
#endif
#ifdef x86_64_has_no_cpu_user_regs
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct cpu_user_regs_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_guest_core_regs");
#ifdef arm32_has_no_vcpu_guest_core_regs
	printf("%8s",
# ifndef arm64_has_no_vcpu_guest_core_regs
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_core_regs_arm32));
	if (sizeof(struct vcpu_guest_core_regs_arm32) != sizeof(struct vcpu_guest_core_regs_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_vcpu_guest_core_regs
	printf("%8s",
# ifndef arm32_has_no_vcpu_guest_core_regs
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_core_regs_arm64));
	if (sizeof(struct vcpu_guest_core_regs_arm64) != sizeof(struct vcpu_guest_core_regs_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_vcpu_guest_core_regs
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_core_regs_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_guest_core_regs
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_core_regs_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_guest_context");
#ifdef arm32_has_no_vcpu_guest_context
	printf("%8s",
# ifndef arm64_has_no_vcpu_guest_context
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_arm32));
	if (sizeof(struct vcpu_guest_context_arm32) != sizeof(struct vcpu_guest_context_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_vcpu_guest_context
	printf("%8s",
# ifndef arm32_has_no_vcpu_guest_context
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_arm64));
	if (sizeof(struct vcpu_guest_context_arm64) != sizeof(struct vcpu_guest_context_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_vcpu_guest_context
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_guest_context
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "arch_vcpu_info");
#ifdef arm32_has_no_arch_vcpu_info
	printf("%8s",
# ifndef arm64_has_no_arch_vcpu_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_arm32));
	if (sizeof(struct arch_vcpu_info_arm32) != sizeof(struct arch_vcpu_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_arch_vcpu_info
	printf("%8s",
# ifndef arm32_has_no_arch_vcpu_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_arm64));
	if (sizeof(struct arch_vcpu_info_arm64) != sizeof(struct arch_vcpu_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_arch_vcpu_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_x86_32));
#endif
#ifdef x86_64_has_no_arch_vcpu_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_time_info");
#ifdef arm32_has_no_vcpu_time_info
	printf("%8s",
# ifndef arm64_has_no_vcpu_time_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_time_info_arm32));
	if (sizeof(struct vcpu_time_info_arm32) != sizeof(struct vcpu_time_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_vcpu_time_info
	printf("%8s",
# ifndef arm32_has_no_vcpu_time_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_time_info_arm64));
	if (sizeof(struct vcpu_time_info_arm64) != sizeof(struct vcpu_time_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_vcpu_time_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_time_info_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_time_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_time_info_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_info");
#ifdef arm32_has_no_vcpu_info
	printf("%8s",
# ifndef arm64_has_no_vcpu_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_info_arm32));
	if (sizeof(struct vcpu_info_arm32) != sizeof(struct vcpu_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_vcpu_info
	printf("%8s",
# ifndef arm32_has_no_vcpu_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct vcpu_info_arm64));
	if (sizeof(struct vcpu_info_arm64) != sizeof(struct vcpu_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_vcpu_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_info_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct vcpu_info_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "arch_shared_info");
#ifdef arm32_has_no_arch_shared_info
	printf("%8s",
# ifndef arm64_has_no_arch_shared_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct arch_shared_info_arm32));
	if (sizeof(struct arch_shared_info_arm32) != sizeof(struct arch_shared_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_arch_shared_info
	printf("%8s",
# ifndef arm32_has_no_arch_shared_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct arch_shared_info_arm64));
	if (sizeof(struct arch_shared_info_arm64) != sizeof(struct arch_shared_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_arch_shared_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct arch_shared_info_x86_32));
#endif
#ifdef x86_64_has_no_arch_shared_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct arch_shared_info_x86_64));
#endif
	printf("\n");

	printf("%-25s |", "shared_info");
#ifdef arm32_has_no_shared_info
	printf("%8s",
# ifndef arm64_has_no_shared_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct shared_info_arm32));
	if (sizeof(struct shared_info_arm32) != sizeof(struct shared_info_arm64))
		printf("!");
#endif
#ifdef arm64_has_no_shared_info
	printf("%8s",
# ifndef arm32_has_no_shared_info
		"!"
# else
		"-"
# endif
	);
#else
	printf("%8zd", sizeof(struct shared_info_arm64));
	if (sizeof(struct shared_info_arm64) != sizeof(struct shared_info_arm32))
		printf("!");
#endif
#ifdef x86_32_has_no_shared_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct shared_info_x86_32));
#endif
#ifdef x86_64_has_no_shared_info
	printf("%8s",
		"-"
	);
#else
	printf("%8zd", sizeof(struct shared_info_x86_64));
#endif
	printf("\n");

	printf("\n");
	exit(0);
}
